(define (magic [p : Integer]) : Integer
  (let ([x (+ 2 3)])
    (let ([y (- 2 (- 1))])
      (let ([z (- 2 (- 1))])
        (let ([a (- 2 (- 1))])
          (let ([b (- 2 (- 1))])
            (let ([c (- 2 (- 1))])
              (let ([d (- 2 (- 1))])
                (let ([e (- 2 (- 1))])
                  (let ([f (- 2 (- 1))])
                      (let ([g (- 2 (- 1))])
                          (let ([h (- 2 (- 1))])
                              (let ([i (- 2 (- 1))])
                                  (let ([j (- 2 (- 1))])
                                      (let ([k (- 2 (- 1))])
                                          (let ([l (- 2 (- 1))])
                    (+ x y z a b c d e f g p i j k l)))))))))))))))))

(magic 31)